name: Build and push Docker image

on:
  push:
    branches:
      - "master"
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          aako/hermod
          ghcr.io/aa-ko/hermod
        tags: |
          type=semver,pattern={{major}}.{{minor}}.{{patch}}
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
